spring:
  application:
    name: Image-Service
  datasource:
    url: jdbc:mysql://localhost:3306/socials_user
    username: root
    password: admin

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka

