spring:
  application:
    name: Image-Service
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
#    url: jdbc:mysql://localhost:3306/user_image
    url: jdbc:mysql://mysql-db:3306/user_image
    username: root
    password: admin

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://naming-server-service:8761/eureka
#      defaultZone: http://localhost:8765/eureka

